// Pulls a curated set of pixelarticons paths into src/icons.generated.ts so icons can be referenced by name (manifests, sidebar).
import { readFileSync, writeFileSync } from "node:fs";
import { createRequire } from "node:module";
import { dirname, join } from "node:path";

const require = createRequire(import.meta.url);
const root = dirname(require.resolve("pixelarticons/package.json"));
const names = [
  "shuffle","repeat","repeat-1","forward","tablet",
  "grid-2x2-2","grid-3x3","grid-2x3","eye-off","file-text","files","phone","monitor","watch","tv","chart-line","chart-bar-big","chart-column-decreasing","sliders-vertical","warning-diamond","lightbulb-off","trending-up","coins","wallet","money","dollar","euro","human","images","image-new","notebook","radio","cloud-moon","cloud-server","sun-solid","power-off","plug-solid","waves","window-frame","colors-swatch","avatar-square","sunglasses","phone-call","building-community",
  "home","layout","sliders","menu","close","check","check-double","plus","minus","trash","save","reload","search","zap","zap-off",
  "sun","moon","cloud","cloud-sun","cloud-moon","wind","thermometer",
  "clock","alarm-clock","calendar","calendar-2","calendar-range","calendar-text","hourglass","bell","bell-ring","bell-off",
  "checkbox","checkbox-on","bulletlist","list-box","note","notes","file","folder","folder-plus","archive","bookmark","label",
  "headphone","camera","gamepad","server","wifi","cellular-signal-3","usb","plug","battery","battery-full","battery-low","power","lightbulb","heart",
  "user","users","avatar-circle","user-plus","lock","key","shield","eye",
  "chevron-up","chevron-down","chevron-left","chevron-right","chevrons-horizontal","chevrons-vertical","arrow-up","arrow-down","arrow-left","arrow-right","external-link","link","unlink","download","upload","open",
  "coffee","car","bus","map","map-pin","flag","trophy","gift","cake","music","play","pause","volume","volume-x","volume-2","volume-3",
  "info-box","circle","square","more-horizontal","more-vertical","drag-and-drop","move","script","code","terminal","cpu","mail","message","comment","chart","analytics","trending-up","wallet","credit-card","store","shopping-bag","image","video","book-open","android","apple","github","git-branch","git-commit","git-merge","git-pull-request","debug","bug","brush","sliders-horizontal","clipboard","copy","scissors","switch","loader","spinner","hourglass",
  "flatten","frame","modem","building","building-community","bed","sofa","printer","tv","alien","sparkles","snowflake","leaf","tree","tree-pine",
];
const out = {};
const missing = [];
for (const n of names) {
  try {
    const svg = readFileSync(join(root, "svg", `${n}.svg`), "utf8");
    const paths = [...svg.matchAll(/<path[^>]*\sd="([^"]+)"/g)].map((m) => m[1]);
    if (paths.length) out[n] = paths;
    else missing.push(n);
  } catch {
    missing.push(n);
  }
}
const src = `// generated by scripts/gen-icons.mjs from pixelarticons (MIT, Gerrit Halfmann). do not edit.
export const ICONS: Record<string, string[]> = ${JSON.stringify(out, null, 0)};
export type IconName = keyof typeof ICONS;
`;
writeFileSync(join(dirname(new URL(import.meta.url).pathname.replace(/^\/([A-Za-z]:)/, "$1")), "../src/icons.generated.ts"), src);
console.log(`wrote ${Object.keys(out).length} icons`, missing.length ? `missing: ${missing.join(", ")}` : "");
